name: Continuous Integration

on:
  push:
    branches: 
    - master

  pull_request:
    branches: 
    - master

jobs:
  linux:
    name: Continuous Integration - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
        - ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - name: Actions - Use CheckOut@V2
      uses: actions/checkout@v2
    - name: Install - Durian Dependencies
      run: shards install
    - name: Test - Crystal Spec
      run: crystal spec --error-trace --stats --progress --no-debug

  macOS:
    name: Continuous Integration - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
        - macOS-latest
    steps:
    - name: Actions - Use CheckOut@V2
      uses: actions/checkout@v2
    - name: TemporaryFix - Brew Package Management (Github/Action#1811)
      run: |
        brew uninstall --force --ignore-dependencies openssl
        brew cleanup -s openssl
        brew cleanup --prune-prefix
        brew install openssl
        brew uninstall --force --ignore-dependencies python
        rm $(which 2to3)
        brew cleanup -s python
        brew cleanup --prune-prefix
        brew install python
    - name: Update - Brew Package Management
      run: brew update
    - name: Install - Crystal Language
      run: brew install crystal
    - name: Install - Durian Dependencies
      run: shards install
    - name: Test - Crystal Spec
      run: crystal spec --error-trace --stats --progress --no-debug
